
export const FLAME_CONTENT = {
  wheel: {
    extreme: {
      male: [
        "Szopd le a párod lassan, minden porcikáját kiélvezve",
        "Vedd a szádba a heréit és kényeztesd őket a nyelveddel",
        "Maszturbálj neki és nézz mélyen a szemébe közben",
        "Kérd meg, hogy élvezzen a szádba, és mindet nyeld le",
        "Nyald végig a faszát a tövétől a leghegyéig lassan",
        "Végezz mélytorkozást rajta, amíg csak bírod",
        "Kérd a párod, hogy pofozzon fel a kezével szex közben",
        "Dörzsöld a puncidat a faszához, amíg mindketten megőrültök",
        "Suttogd a fülébe: 'Tiéd vagyok, bassz meg vadul'",
        "Hagyd, hogy a párod a melleid közé élvezzen",
        "Maszturbálj a párod előtt, és közben mondd: 'Nézd, mennyire kívánlak'",
        "Nyald végig a gátját a heréitől felfelé",
        "Harapj bele a heréibe finoman, és szívd meg őket",
        "Vegyél egy jégkockát a szádba, és úgy szopd le a párod",
        "Szopd le a párod faszát közben játszva a punciddal",
        "Hagyd, hogy a párod a hasadra élvezzen",
        "Köpd le a faszát, mielőtt elkezdenéd leszopni",
        "Verd ki neki síkosítóval vagy olajjal, amíg el nem élvez",
        "Vedd a szádba a heréit és kényeztesd őket a nyelveddel",
        "Kérd meg, hogy élvezzen a szádba és mutasd meg neki",
        "Nyald meg a fasza hegyét és szívd meg cuppogósan",
        "Suttogd: 'Imádom a faszod ízét'",
        "Harapj a combba a fasza mellett, és nyald meg a nyomot",
        "Verd ki neki két kézzel, vadul rángatva",
        "Nyald meg a heréit, majd fújj rájuk meleg levegőt",
        "Kérd meg, hogy hívjon a k*rvájának, miközben szopod",
        "Dugd be az ujjad a saját puncidba, miközben őt szopod",
        "Maszturbálj neki az ölében ülve",
        "Nyald végig a testét a lábujjától a faszáig",
        "Hagyd, hogy a szádba élvezzen mélyen",
        "Nyald meg a heréit, majd harapdáld meg őket óvatosan",
        "Verd ki neki szappan segítségével a zuhany alatt",
        "Suttogd a fülébe: 'Bármit megteszek érted'",
        "Nyald meg a faszát, és szívd be a torkodig",
        "Harapj a fenekébe és hagyd, hogy lefogjon",
        "Vedd a szádba a párod faszát és mozgasd rajta lassan a nyelved",
        "Kérd meg, hogy köpjön a szádba szopás előtt",
        "Maszturbálj neki és közben suttogj mocskos dolgokat",
        "Nyald meg a heréit, majd szívd be őket a szádba",
        "Verd ki neki sebességet váltogatva: lassú, gyors, lassú",
        "Hagyd, hogy a párod a hajadat húzza szopás közben",
        "Kérd a párod, hogy fojtogasson finoman, miközben vered neki",
        "Nyald meg a faszát a tövénél körbe",
        "Suttogd: 'Olyan kemény vagy, teljesen megőrjítesz'",
        "Harapj a combjába, majd nyald le a nyálat róla",
        "Verd ki neki lassan, minden rezdülését figyelve",
        "Vedd a szádba a heréit és szívd meg őket hosszan",
        "Kérd a párod, hogy élvezzen az arcodra",
        "Nyald meg a fasza hegyét, majd fújj rá hideg levegőt",
        "Maszturbálj neki vizes kézzel",
        "Suttogd: 'Bassz meg úgy, hogy elfelejtsem a nevem'",
        "Harapj a heréi közé óvatosan",
        "Verd ki neki gyorsan, amíg el nem pirosodik",
        "Vedd a szádba és tarts ott mélyen 10 másodpercig",
        "Nyald végig a gátját lassan",
        "Kérd meg, hogy élvezzen a puncidra",
        "Maszturbálj neki, miközben ő a melleidet fogja",
        "Suttogd: 'Olyan mocsok vagy, akit imádok'",
        "Nyald meg a heréit, majd fújj rájuk meleg levegőt",
        "Harapj bele a fenekébe játékosan",
        "Verd ki neki olajjal, amíg minden csupa mocsok nem lesz",
        "Vedd a szádba és pörögj rajta a nyelveddel",
        "Kérd meg, hogy élvezzen a füledbe suttogva",
        "Nyald meg a faszát, majd harapj rá az ajkadra",
        "Maszturbálj neki vadul, amíg el nem kezd remegni",
        "Suttogd: 'Tiéd minden lyukam, tégy velem bármit'",
        "Harapj a combjába, majd nyald meg a sebedet",
        "Vedd a szádba és szippants rá nagyot",
        "Nyald végig a hasát felfelé",
        "Kérd meg, hogy nevezzen a rabszolgájának",
        "Verd ki neki két kézzel, mintha az életed múlna rajta",
        "Nyald meg a heréit, majd suttogj valami perverzet",
        "Hagyd, hogy a szádba élvezzen és játssz vele a nyelveddel",
        "Harapj a fasza tövébe finoman",
        "Vedd a szádba és mozgasd a fejed előre-hátra gyorsan",
        "Nyald meg a gátját, majd szívd meg a heréit",
        "Kérd meg, hogy élvezzen a hasadra",
        "Maszturbálj neki és közben nyald meg a saját ujjad",
        "Suttogd: 'Imádom, ha durva vagy velem'",
        "Nyald meg a faszát, majd fújj rá meleg levegőt",
        "Harapj a fenekébe és kapaszkodj bele",
        "Verd ki neki lassan, majd hirtelen gyorsíts be",
        "Vedd a szádba és szívd meg cuppogósan 5-ször",
        "Nyald végig a heréit alulról",
        "Kérd meg, hogy hívjon a k*rvájának",
        "Maszturbálj neki és közben mutasd meg, mennyire nedves vagy",
        "Suttogd: 'Olyan jó a faszod íze'",
        "Nyald meg a faszát lassan",
        "Harapj a combjába és szívd meg a bőrt",
        "Verd ki neki síkosítóval, amíg el nem élvez az öledbe",
        "Vedd a szádba és nyeld le a torkodig",
        "Nyald meg a heréit egyenként",
        "Kérd meg, hogy élvezzen a hasadra",
        "Maszturbálj neki és közben nézz az ölébe",
        "Suttogd: 'Bassz meg mélyen'",
        "Nyald meg a faszát, majd szívd meg a heréit",
        "Harapj a fenekébe keményen",
        "Verd ki neki gyorsan 1 percig",
        "Vedd a szádba és ne engedd el",
        "Nyald végig a testét a nyakától a faszáig"
      ],
      female: [
        "Nyald ki a párod punciját lassan, minden centit kiélvezve",
        "Ülj az arcára és hagyd, hogy a nyelve a puncidban legyen",
        "Ujjazd meg a párod vadul, amíg el nem száll az agya",
        "Használj vibrátort rajta, amíg el nem kezd sikoltozni",
        "Nyald végig a puncit az ajkak mentén lassan",
        "Dugd be az ujjad mélyen a puncijába és ujjazd meg vadul",
        "Harapj bele a fenekébe és hagyj rajta fognyomot",
        "Köpd le a puncit, mielőtt elkezdenéd kinyalni",
        "Suttogd a fülébe: 'Te vagy az én kis k*rvám'",
        "Csapkodd meg a seggét, amíg vörös nem lesz",
        "Dörzsöld a puncidat az arcához vagy az ő puncijához",
        "Mutasd meg neki, hogyan ujjazd meg magad ilyen vadul",
        "Nyald meg a csiklóját és szívd meg hosszan",
        "Maszturbálj az arcára vagy a melleire",
        "Nyald le a tejszínhabot a punciról",
        "Szipogasd meg a puncit közvetlen közelről",
        "Használd a nyelvedet a csiklóján körkörös mozdulatokkal",
        "Kérd meg, hogy ujjazzon meg téged, miközben te kinyalod",
        "Köpd le a csiklóját és dörzsöld bele a nyelveddel",
        "Mondd neki: 'Olyan nedves vagy, te kis dög'",
        "Dörgöld az arcodat a szeméremajkaihoz",
        "Dugd bele három ujjad a puncijába és ujjazd meg, amíg remegni nem kezd",
        "Harapd meg a combját a puncija mellett",
        "Maszturbáljatok egymás előtt, és nézzétek egymást",
        "Kérd meg, hogy pofozzon le, miközben ujjazod őt",
        "Suttogd: 'Ennél szűkebbet még nem éreztem'",
        "Ujjazd meg hátulról, miközben a hajat rángatod",
        "Harapj bele a mellbimbójába, miközben a csiklóját izgatod",
        "Nyald a punciját cikkcakkban végig",
        "Használj jégkockát a csiklóján, majd nyald le a vizet",
        "Kérd meg, hogy nevezzen a rabszolgájának",
        "Nyald meg a csiklóját és szívd meg, amíg fel nem sikolt",
        "Dörzsöld a puncidat az arcához, és élvezz rá",
        "Suttogd: 'Te vagy a legmocskosabb vágyam'",
        "Dugd be az ujjad lassan, majd hirtelen ujjazd meg durván",
        "Nyald a szeméremajkait és szívd be őket a szádba",
        "Harapd meg az ajkát, miközben elélvez a nyelvedtől",
        "Nyald ki a punciját úgy, hogy közben meg-megcsapkodod a fenekét",
        "Mondd neki: 'Olyan büdös a vágytól, imádom'",
        "Vezesd bele az ujjaidat a puncijába, amíg a nedve a kezedre nem folyik",
        "Nyald meg a csiklóját, majd harapj rá finoman",
        "Kérd meg, hogy élvezzen az ujjadra, és kend el az arcodon",
        "Ujjazd meg, miközben a melleit fogod",
        "Nyald végig a testét a puncitól a szájáig",
        "Harapj bele a fenekébe, miközben ő maszturbál neked",
        "Nyald meg a csiklóját és szívd meg, mintha az életed múlna rajta",
        "Suttogd: 'Dugd belém az ujjad, mélyebbre'",
        "Ujjazd meg a mellei között szorítva",
        "Használd a vibrátort a szeméremajkain",
        "Kérd meg, hogy húzza hátra a karod, miközben kinyalod",
        "Nyald meg a csiklóját, majd fújj rá meleg levegőt",
        "Mondd neki: 'Te vagy a legmocskosabb punci a világon'",
        "Ujjazd meg hátulról, miközben a derekát fogod",
        "Nyald ki a párod punciját és dörzsöld az arcodat hozzá",
        "Maszturbálj előtte, és kend a nedved a szájába",
        "Nyald meg a két ajkát, majd szívd be a csiklóját",
        "Suttogd: 'Imádom, ha nedves vagy tőlem'",
        "Harapj a combjába lassan",
        "Ujjazd meg két kézzel egyszerre",
        "Nyald végig a gátját a puncitól felfelé",
        "Kérd meg, hogy élvezzen a szájadba",
        "Maszturbálj neki és közben suttogj mocskos dolgokat",
        "Nyald meg a csiklóját sokat egymás után",
        "Harapj a fenekébe keményen",
        "Ujjazd meg, amíg remegni nem kezd a lába",
        "Nyald ki a punciját és közben nyúlj bele a szájába",
        "Mondd neki: 'Bármit megteszek a puncidért'",
        "Ujjazd meg sebességet váltogatva",
        "Nyald meg a csiklóját és közben fojtogasd finoman",
        "Harapj a melleibe játékosan",
        "Használj vibrátort és közben ujjazd is",
        "Kérd meg, hogy hívjon a k*rvájának",
        "Nyald végig a testét a nyelvhegyeddel",
        "Ujjazd meg síkosítóval mélyen",
        "Suttogd: 'Te vagy az örök vágyam'",
        "Nyald meg a csiklóját és mozgasd rajta a nyelved gyorsan",
        "Harapj a combja belső felébe",
        "Ujjazd meg lassítva, minden rezdülésre figyelve",
        "Nyald ki a punciját és kapaszkodj belé",
        "Kérd meg, hogy élvezzen a puncidra",
        "Maszturbálj neki az ölében",
        "Nyald meg a szeméremajkait cuppogva",
        "Harapj a fenekébe és szorítsd meg",
        "Dugd bele az ujjad és ujjazd meg mélyen",
        "Nyald ki a punciját, amíg el nem dől",
        "Mondd neki: 'Te vagy a legszűkebb'",
        "Nyald meg a csiklóját és szívd meg hosszan",
        "Harapj a combjába",
        "Ujjazd meg hátulról vadul",
        "Nyald végig a testét",
        "Kérd meg, hogy élvezzen az arcodra",
        "Maszturbálj előtte",
        "Nyald meg a csiklóját",
        "Harapj a fenekébe",
        "Ujjazd meg őt mélyen",
        "Nyald ki a punciját",
        "Mondd neki valami perverzet",
        "Suttogd: 'Kérlek ujjazz meg'",
        "Nyald meg a szeméremajkait",
        "Harapj a combjába"
      ]
    }
  },
  decks: [
    { 
      id: 'romantic', 
      name: 'Mocskos Romantika', 
      color: 'from-pink-500 to-rose-500', 
      icon: 'Heart', 
      content: {
        extreme: {
          male: [
            "Mondd el, hova élveznék legszívesebben ma éjjel a testeden",
            "Melyik pózban látnád legszívesebben a faszomat a szádban?",
            "Hogy érzed magad, amikor mélyen a torkodba nyomom?",
            "Mi az a legbetegebb vágyad, amit velem szeretnél átélni?",
            "Szereted, ha k*rvának szólítalak, miközben szopod?",
            "Hogy éreznéd magad, ha most rögtön leköpném a puncidat?",
            "Melyik testrészemre élveznél a legszívesebben ma este?",
            "Suttogd el, hova dugnád be az ujjadat most rögtön",
            "Hogy éreznéd magad, ha megbilincselnélek szex közben?",
            "Mondd ki a nevemet, miközben a faszomat szopod",
            "Szereted, ha durván pofon váglak a kezemmel szex közben?",
            "Hogy éreznéd magad, ha az arcomra élveznél a szemembe nézve?",
            "Mi az a mocsok dolog, amitől rögtön feláll a faszod?",
            "Szeretnéd, ha ma este csak a puncidat dugnám vadul?",
            "Hogy éreznéd magad, ha bekötném a szemedet és úgy szopnál le?",
            "Szereted, ha a hajadat húzom, miközben mélyen beléd hatolok?",
            "Hogy éreznéd magad, ha ma éjjel csak a konyhában szexelnénk?",
            "Suttogd el, hogy mennyire vágysz a nyelvemre a gátadon",
            "Mi az a dolog, amit csak az ágyban, a legnagyobb mocsokban mersz elárulni?",
            "Hogy éreznéd magad, ha leköpnélek és úgy dugnálak meg?",
            "Mondd el: 'Tiéd vagyok, tégy velem amit akarsz'",
            "Melyik pillanatban élveznél el a legszívesebben a szádba?",
            "Hogy érzed magad, ha a faszomat az arcodhoz dörzsölöm?",
            "Mi az a mocsok dolog, amit még sosem kértél tőlem?",
            "Szereted, ha a puncidba nyomom az ujjamat kérés nélkül?",
            "Hogy éreznéd magad, ha leköpnélek szex közben?",
            "Mondd ki: 'Bassz meg mélyen te állat'",
            "Szeretnéd, ha ma éjjel tabuk nélkül szexelnénk?",
            "Hogy éreznéd magad, ha a faszommal simogatnám a nyelvedet?",
            "Mondd el, hova élvezzek ma, hogy örökre érezd",
            "Szereted, ha a hajadat rángatom, miközben a torkodig hatolok?",
            "Hogy éreznéd magad, ha megverném a puncidat vörösre?",
            "Mondd ki: 'Te vagy az én legmocskosabb uram'",
            "Szeretnéd, ha a nyelvemmel nyúlnék be a puncidba?",
            "Hogy éreznéd magad, ha ma éjjel nem hagynálak aludni?",
            "Mondd el, mi a legbetegebb fantáziád a melleimmel",
            "Szereted, ha a heréimmel játszol a szádban?",
            "Hogy éreznéd magad, ha bekötném a szemedet és úgy kényeztetnél?",
            "Mondd ki: 'Imádom a mocsok ízedet'",
            "Szeretnéd, ha a faszom hegyével vágnám pofon a puncidat?",
            "Hogy éreznéd magad, ha ma este a padlón dugnálak meg?",
            "Mondd el, hova dugnád be az ujjadat a heréimnél",
            "Szereted, ha a nyelvemmel tiszítanám ki a puncidat?",
            "Hogy éreznéd magad, ha ma éjjel megbilincselnélek?",
            "Mondd ki: 'Kérlek hadd szopjam le a faszodat'",
            "Szeretnéd, ha a heréim az arcodon pihennének?",
            "Hogy éreznéd magad, ha ma este a melleid közé élveznék?",
            "Mondd el, miért vágysz annyira a faszomra",
            "Szereted, ha a nyelvemmel nyalnék végig a puncidról a szádba?",
            "Hogy éreznéd magad, ha ma éjjel én lennék a rabszolgád?",
            "Mondd ki: 'Ujjazz meg mélyen, te k*rva'",
            "Szeretnéd, ha a fülembe suttognád a mocsok vágyaidat?",
            "Hogy éreznéd magad, ha ma este a konyhában szopnál le?",
            "Mondd el, hova tennéd a nyelvedet a faszomon?",
            "Szereted, ha a faszommal verem a fogadat?",
            "Hogy éreznéd magad, ha ma éjjel bekötném a szádat?",
            "Mondd ki: 'Te vagy az én legperverzebb szerelmem'",
            "Szeretnéd, ha a puncidba üríteném minden vágyamat?",
            "Hogy éreznéd magad, ha ma este az arcodra ülnék szex közben?",
            "Mondd el, miért szereted, ha k*rvának hívlak",
            "Szereted, ha a heréimet beveszed a szádba?",
            "Hogy éreznéd magad, ha ma éjjel a zuhany alatt ujjaznál meg?",
            "Mondd ki: 'Imádom a faszod ízét'",
            "Szeretnéd, ha a nyelvemmel nyúlnék a torkodba?",
            "Hogy éreznéd magad, ha ma este leborotválnám a puncidat?",
            "Mondd el, mi a legmocskosabb szó, amit ismersz",
            "Szereted, ha a faszommal simogatom a puncidat?",
            "Hogy éreznéd magad, ha ma éjjel megerőszakolnád a puncimat?",
            "Mondd ki: 'Én vagyok a te kis dögöd'",
            "Suttogd el: 'Bassz meg amíg el nem ájulok'",
            "Mondd el, melyik pózban élveznél el most rögtön",
            "Szereted, ha a heréimet az arcodhoz szorítom?",
            "Mondd ki: 'Imádom a faszodat'",
            "Suttogd: 'Olyan sexy vagy'",
            "Hogy éreznéd magad, ha ma este csak a nyelvedet használhatnád?",
            "Mondd el, hova dugnád a faszomat a legszívesebben",
            "Szereted, ha a melleid közé dugom?",
            "Mondd ki: 'Bassz meg mélyen'",
            "Suttogd el a legperverzebb vágyad",
            "Hogy éreznéd magad, ha leköpnélek?"
          ],
          female: [
            "Nyald ki a párod punciját az asztal alatt mindenki előtt",
            "Melyik pózban látnád legszívesebben a puncimat?",
            "Hogy érzed magad, amikor az ujjamat a puncidba nyomom?",
            "Mi az a legbetegebb vágyad, amit velem szeretnél átélni?",
            "Szereted, ha k*rvának szólítalak, miközben kinyallak?",
            "Hogy éreznéd magad, ha most rögtön leköpném a puncidat?",
            "Melyik testrészemre élveznél a legszívesebben ma este?",
            "Suttogd el, hova dugnád be az ujjadat most rögtön",
            "Hogy éreznéd magad, ha megbilincselnélek szex közben?",
            "Mondd ki a nevemet, miközben a puncimat nyalod",
            "Szereted, ha durván pofon váglak szex közben?",
            "Hogy éreznéd magad, ha a szemembe néznél, miközben elélvezel?",
            "Mi az a mocsok dolog, amitől rögtön elázik a puncid?",
            "Szeretnéd, ha ma este csak az ujjadat használnád?",
            "Hogy éreznéd magad, ha bekötném a szemedet és úgy nyalnálak ki?",
            "Szereted, ha a hajadat húzom, miközben az ujjammal kényeztetlek?",
            "Hogy éreznéd magad, ha ma éjjel csak a melleinkkel játszanánk?",
            "Suttogd el, hogy mennyire vágysz a nyelvemre a csiklódon",
            "Mi az a dolog, amit csak az ágyban, a legnagyobb mocsokban mersz elárulni?",
            "Hogy éreznéd magad, ha leköpnélek és úgy ujjaznál meg?",
            "Mondd el: 'Te vagy az én kis mocskos rabszolgám'",
            "Melyik pillanatban élveznél el a legszívesebben a puncimba?",
            "Hogy érzed magad, ha a puncimat az arcomhoz dörzsölöm?",
            "Mi az a mocsok dolog, amit még sosem kértél tőlem?",
            "Szereted, ha a puncidba nyomom az ujjamat kérés nélkül?",
            "Hogy éreznéd magad, ha leköpnélek szex közben?",
            "Mondd ki: 'Ujjazz meg mélyen te k*rva'",
            "Szeretnéd, ha ma éjjel tabuk nélkül szexelnénk?",
            "Hogy éreznéd magad, ha a puncimmal simogatnám a nyelvedet?",
            "Mondd el, hova élvezzek ma, hogy örökre érezd",
            "Szereted, ha a hajadat rángatom, miközben a puncidba ujjazok?",
            "Hogy éreznéd magad, ha megverném a melleidet vörösre?",
            "Mondd ki: 'Te vagy az én legmocskosabb úrnőm'",
            "Szeretnéd, ha a nyelvemmel nyúlnék be a puncidba?",
            "Hogy éreznéd magad, ha ma éjjel nem hagynálak aludni?",
            "Mondd el, mi mi a legbetegebb fantáziád a testemmel",
            "Szereted, ha a puncimmal játszol a szádban?",
            "Hogy éreznéd magad, ha bekötném a szemedet és úgy ujjaznál meg?",
            "Mondd ki: 'Imádom a mocsok ízedet'",
            "Szeretnéd, ha a csiklómmal vágnám pofon a puncidat?",
            "Hogy éreznéd magad, ha ma este a padlón nyalnálak ki?",
            "Mondd el, hova dugnád be az ujjadat a csiklóm mellett",
            "Szereted, ha a nyelvemmel tiszítanám ki a puncidat?",
            "Hogy éreznéd magad, ha ma éjjel megbilincselnélek?",
            "Mondd ki: 'Kérlek ujjazz meg mélyen, te dög'",
            "Szeretnéd, ha a puncim az arcodon pihenne?",
            "Hogy éreznéd magad, ha ma este a melleid közé élveznék?",
            "Mondd el, miért vágysz annyira a puncimra",
            "Szereted, ha a nyelvemmel nyalnék végig a puncidról a szádba?",
            "Hogy éreznéd magad, ha ma éjjel én lennék a rabszolgád?",
            "Mondd ki: 'Nyald ki a puncimat, te k*rva'",
            "Szeretnéd, ha a fülembe suttognád a mocsok vágyaidat?",
            "Hogy éreznéd magad, ha ma este a konyhában ujjaznál meg?",
            "Mondd el, hova tennéd a nyelvedet a puncimon?",
            "Szereted, ha a csiklómmal verem a fogadat?",
            "Hogy éreznéd magad, ha ma éjjel bekötném a szádat?",
            "Mondd ki: 'Te vagy az én legperverzebb szerelmem'",
            "Szeretnéd, ha a puncidba üríteném minden vágyamat?",
            "Hogy éreznéd magad, ha ma este az arcodra ülnék szex közben?",
            "Mondd el, miért szereted, ha k*rvának hívlak",
            "Szereted, ha a puncimat beveszed a szádba?",
            "Hogy éreznéd magad, ha ma éjjel a zuhany alatt nyalnálak ki?",
            "Mondd ki: 'Imádom a csiklód ízét'",
            "Szeretnéd, ha a nyelvemmel nyúlnék a puncidba?",
            "Hogy éreznéd magad, ha ma este leborotválnám a puncidat?",
            "Mondd el, mi a legmocskosabb szó, amit ismersz",
            "Szereted, ha a puncimmal simogatnám a puncidat?",
            "Hogy éreznéd magad, ha ma éjjel megerőszakolnál a nyelveddel?",
            "Mondd ki: 'Én vagyok a te kis dögöd'",
            "Suttogd el: 'Ujjazz meg amíg el nem ájulok'",
            "Mondd el, melyik pózban élveznél el most rögtön",
            "Szereted, ha a puncimat az arcodhoz szorítom?",
            "Mondd ki: 'Imádom a puncidat'",
            "Suttogd: 'Olyan mocsok vagy'",
            "Hogy éreznéd magad, ha ma este csak a nyelvedet használhatnád?",
            "Mondd el, hova dugnád az ujjadat a legszívesebben",
            "Szereted, ha a melleid közé dörzsölöm?",
            "Mondd ki: 'Ujjazz meg mélyen'",
            "Suttogd el a legperverzebb vágyad",
            "Hogy éreznéd magad, ha leköpnélek?"
          ]
        }
      }
    },
    { 
      id: 'spicy', 
      name: 'Vérbeli Szenvedély', 
      color: 'from-orange-500 to-rose-600', 
      icon: 'Zap', 
      content: {
        extreme: {
          male: [
            "Szopd le a párod most rögtön 2 percig gátlások nélkül",
            "Húzd le a párod gatyáját a fogaiddal és nyald meg a faszát",
            "Tedd a kezedet a párod faszára a nadrágon át és szorítsd meg",
            "Nyald végig a gátját lassan, meg-megállva közben",
            "Suttogd a fülébe, hogy mennyire akarod a faszát mélyre",
            "Harapj bele a heréibe finoman, és suttogj valami perverzet",
            "Hagyd, hogy az arcodra üljön a faszával",
            "Verd ki neki lassan, nézve ahogy megfeszül",
            "Nyald végig a combját a fasza mellett",
            "Öntsd le meleg olajjal a faszát és úgy szopd le",
            "Maszturbálj neki és élvezz a kezére",
            "Pofozd fel a párod, ha nem engedelmeskedik a vágyaidnak",
            "Vedd a szádba a fasza hegyét és pörögj rajta a nyelveddel",
            "Hagyd, hogy a szájadba élvezzen és mindet nyeld le",
            "Dörzsöld a puncidat a faszához vadul",
            "Nyald meg a faszát a tövétől a torkodig hosszan",
            "Kérd meg, hogy hívjon k*rvának, miközben szopod",
            "Verd ki neki szappan vagy olaj segítségével",
            "Döfködd az arcát a melleiddel vagy kérd tőle a faszát",
            "Vedd a szádba és ne engedd el, amíg nem élvez",
            "Nyald meg a heréit, majd szívd meg a fasza hegyét hirtelen",
            "Verd ki neki a két melled között, miközben ő fojtogat",
            "Dugd be a nyelvedet a fasza hegye alá és mozgasd gyorsan",
            "Harapj a heréi közé, majd nyald meg a helyét",
            "Kérd meg, hogy köpjön a szájadba, mielőtt leszopod",
            "Maszturbálj neki, amíg az ondója szét nem fröccsen",
            "Nyald végig a gátját, miközben ő a puncidat újjazza",
            "Harapj a combjába, majd nyald meg a puncit",
            "Verd ki neki lábbal, miközben a heréivel játszol",
            "Nyald meg a fasza hegyét, majd fújj rá hideg levegőt",
            "Suttogd neki: 'Olyan mocsok vagy, mint egy állat'",
            "Dugd be az öklödet a szájába, miközben ő szopja a melledet",
            "Nyald meg a heréit, majd mutasd meg a nyelvedet",
            "Harapj a faszába játékosan, de figyelve rá",
            "Verd ki neki két kézzel, vadul rángatva a bőrt",
            "Nyald meg a heréit, majd szívd be őket a szádba",
            "Kérd meg, hogy élvezzen a füledbe suttogva",
            "Dörgöld a puncidat a faszához vadul",
            "Nyald meg a faszát, amíg el nem lazul teljesen",
            "Harapj a combjába a heréi mellett",
            "Verd ki neki olajjal, amíg minden csupa mocsok nem lesz",
            "Nyald meg a faszát, majd harapj rá az ajkadra",
            "Kérd meg, hogy hívjon a k*rvájának szex közben",
            "Maszturbálj neki, és élvezz a faszának hegyére",
            "Nyald meg a heréit, miközben ő a hajadat rángatja",
            "Harapj a faszába, majd nyald le a nyálat róla",
            "Verd ki neki gyorsan, majd hirtelen állj meg",
            "Nyald meg a heréit, majd harapdáld meg őket",
            "Kérd meg, hogy pofozzon le a kezével",
            "Nyald meg a faszát suttogva valami perverzet",
            "Harapj a fenekébe, majd szívd meg a bőrt",
            "Verd ki neki szappan segítségével a zuhany alatt",
            "Nyald meg a gátját, majd szívd ki a vágyat",
            "Kérd meg, hogy élvezzen a szemedbe",
            "Maszturbálj neki, miközben ő a puncidat újjazza",
            "Nyald meg a faszát, majd fojtogassátok egymást",
            "Harapj a fasza hegyének tövébe keményen",
            "Verd ki neki lassítva, minden rezzenését figyelve",
            "Nyald meg a heréit, majd fújj rájuk meleg levegőt",
            "Kérd meg, hogy nevezzen a rabszolgájának",
            "Maszturbálj neki, amíg ő el nem élvez",
            "Nyald meg a heréit, miközben ő az arcodba élvez",
            "Harapj a combjába, majd nyald meg a faszát",
            "Verd ki neki a két combod között szorosan",
            "Nyald meg a fasza hegyét, majd szívd meg cuppogva",
            "Kérd meg, hogy köpje le a faszát, majd szopd le",
            "Maszturbálj előtte, és kend be az arcát vágyaddal",
            "Nyald meg a heréit hosszan, amíg el nem élvez",
            "Suttogd el: 'Tiéd vagyok egészen, te állat'",
            "Nyald meg a faszát suttogva valami mocskosat",
            "Mondd el: 'Bármit megteszek a faszodért'",
            "Harapj a faszába, és nyald le a vágyát",
            "Verd ki neki, miközben leköpöd a heréit",
            "Nyald meg a faszát, és mondd: 'Finom'",
            "Ujjazz meg párszor, miközben őt szopod",
            "Kérd meg, hogy élvezzen a torkodra",
            "Nyald meg a faszát, és szívd be a torkodig",
            "Suttogd: 'Olyan izgató és jó a faszod'",
            "Verd ki neki vadul, amíg el nem dől",
            "Nyald meg a heréit mélyen",
            "Harapj a faszába, amíg fel nem rándul",
            "Kérd meg, hogy élvezzen a puncidra",
            "Maszturbálj neki, és élvezz elé",
            "Nyald meg a heréit, és harapdáld",
            "Verd ki neki olajjal a melleidnél",
            "Nyald meg a faszát hosszan",
            "Suttogd: 'Bassz meg mélyen'",
            "Nyald meg a heréit lassan",
            "Harapj a combjába erősen",
            "Verd ki neki gyorsan",
            "Vedd a szádba mélyen",
            "Nyald végig a heréit",
            "Kérd meg, hogy élvezzen a szádba",
            "Maszturbálj előtte vadul",
            "Suttogd: 'Imádom a faszod'",
            "Nyald meg a fasza hegyét"
          ],
          female: [
            "Nyald ki a párod most rögtön 2 percig gátlások nélkül",
            "Húzd le a párod bugyiját a fogaiddal és nyald meg a punciját",
            "Tedd a kezedet a párod puncijára a nadrágon át és szorítsd meg",
            "Nyald végig a gátját lassan, meg-megállva közben",
            "Suttogd a fülébe, hogy mennyire akarod, hogy ujjazzon meg mélyen",
            "Harapj bele a csiklójába finoman, és suttogj valami perverzet",
            "Ülj az arcára és hagyd, hogy a nyelve a puncidban legyen",
            "Ujjazd meg a punciját lassan, ujjbeggyel izgatva",
            "Nyald végig a combját a puncija mellett",
            "Öntsd le meleg olajjal a punciját és úgy nyald ki",
            "Maszturbálj neki és élvezz a kezére",
            "Pofozd fel a párod, ha nem engedelmeskedik a vágyaidnak",
            "Vedd a szádba a csiklóját és szívd meg cuppogósan",
            "Hagyd, hogy elélvezzen a nyelveddel",
            "Dörzsöld a puncidat a puncijához vadul",
            "Nyald meg a punciját a gátjától felfelé hosszan",
            "Kérd meg, hogy hívjon k*rvának, miközben kinyalod",
            "Verd ki a punciját szappan vagy olaj segítségével",
            "Döfködd az arcát a punciddal",
            "Nyald ki a punciját és ne engedd el, amíg el nem élvez",
            "Nyald meg a csiklóját, majd szívd meg hirtelen",
            "Ujjazd meg, amíg el nem ázol tőle",
            "Harapj a combjába, majd nyald ki a vágyad",
            "Kérd meg, hogy köpjön a puncidra, majd kend szét",
            "Ujjazd meg két ujjal egyszerre",
            "Nyald ki a punciját cikkcakkban, vadul",
            "Harapj a fenekébe, majd ujjazd meg a puncit",
            "Mondd neki: 'Olyan mocskos vagy, te kis dög'",
            "Nyald meg a csiklóját, majd fújj rá hideg levegőt",
            "Ujjazd meg hátulról, miközben a hajat rángatod",
            "Harapj a mellbimbójába, miközben kinyalod",
            "Maszturbálj az arcára, és élvezz rá",
            "Nyald meg a szeméremajkait hosszan",
            "Kérd meg, hogy nevezzen a rabszolgájának",
            "Ujjazd meg olajjal, amíg remegni nem kezd",
            "Nyald meg a csiklóját, majd harapdáld meg a fenekét",
            "Harapj az ajkára, miközben ujjazod a puncit",
            "Nyald ki a punciját, amíg el nem száll az agya",
            "Harapj a melleibe, miközben kinyalod",
            "Ujjazd meg lassítva, minden centit élvezve",
            "Nyald meg a csiklóját, majd szívd be a szájadba",
            "Kérd meg, hogy pofozzon le a kezével",
            "Maszturbálj előtte, és kend be a vágyaddal",
            "Nyald meg a puncit, miközben ő nevet",
            "Harapj a combjának belső felébe keményen",
            "Ujjazd meg, és közben ujjazz magadba is",
            "Nyald ki a punciját, amíg el nem élvez rajtad",
            "Harapj a fenekébe, majd szívd meg a nyomot",
            "Ujjazd meg szappan segítségével a zuhany alatt",
            "Nyald meg a gátját, majd szívd ki az ízét",
            "Kérd meg, hogy élvezzen az arcodra",
            "Maszturbálj neki, miközben ő a csiklódat ujjazza",
            "Nyald meg a puncit, majd fojtogassátok egymást",
            "Harapj a csiklója tövébe, és szívd meg",
            "Ujjazd meg hátulról, miközben a derekát fogod",
            "Nyald ki a punciját, amíg el nem sötétül minden",
            "Harapj a fenekébe, majd nyald meg a sebedet",
            "Ujjazd meg lassítva, figyelve az arcát",
            "Nyald meg a csiklóját, majd fújj rá meleg levegőt",
            "Kérd meg, hogy nevezzen a legmocskosabb k*rvájának",
            "Maszturbálj neki, amíg el nem sül",
            "Nyald meg a puncit, miközben ő az öledben van",
            "Harapj a combjába, majd ujjazd meg őt",
            "Ujjazd meg mélyen, és nézz a szemébe",
            "Nyald meg a punciját, majd szívd meg a mocsok ízét",
            "Suttogd el: 'Tiéd mindenem, te dög'",
            "Nyald ki a csiklóját suttogva valami mocskot",
            "Mondd el: 'Bármit megteszek a puncidért'",
            "Harapj a csiklójába, és nyald le a vágyát",
            "Ujjazd meg, miközben leköpöd a puncit",
            "Nyald meg a puncit, és mondd: 'Mocskos'",
            "Ujjazd meg, miközben kinyalod",
            "Kérd meg, hogy élvezzen az ujjadra",
            "Nyald meg a csiklóját, és szívd be hosszan",
            "Suttogd: 'Olyan izgató és jó a puncid'",
            "Ujjazd meg vadul, amíg el nem ájul",
            "Nyald ki a puncit mélyen",
            "Harapj a csiklójába, amíg fel nem rándul",
            "Kérd meg, hogy élvezzen a szádba",
            "Maszturbálj neki, és élvezz a kezére",
            "Nyald meg a szeméremajkait, és harapdáld",
            "Ujjazd meg olajjal a melleinél",
            "Nyald ki a punciját hosszan",
            "Suttogd: 'Ujjazz meg mélyen'",
            "Nyald meg a csiklóját lassan",
            "Harapj a combjába erősen",
            "Ujjazd meg gyorsan",
            "Nyald meg a puncit mélyen",
            "Harapj a fenekébe játékosan",
            "Ujjazd meg őt vadul",
            "Suttogd: 'Imádom a puncid'",
            "Nyald meg a szeméremajkait"
          ]
        }
      }
    }
  ]
};
